vnf-rp:
    hosts: 
        vnf-rp1: 
            ansible_host:  192.168.56.101
            ansible_ssh_user:  quobis
            ansible_ssh_pass: asterisk
            ansible_python_interpreter: /usr/bin/python3
            ansible_become_pass: asterisk
            #ansible_ssh_private_key_file: /home/quobis/.ssh/id_rsa
vnf-ms:
    hosts:
        vnf-ms1: 
            ansible_host:  192.168.56.101
            ansible_ssh_user: quobis
            ansible_ssh_pass: asterisk
            ansible_python_interpreter: /usr/bin/python3
            ansible_become_pass: securePass
            #ansible_ssh_private_key_file: /home/quobis/.ssh/id_rsa

vnf-wac:
    hosts:
        vnf-wac1: 
            ansible_host:  192.168.56.101
            ansible_ssh_user:  quobis
            ansible_ssh_pass: asterisk
            ansible_python_interpreter: /usr/bin/python3
            ansible_become_pass: securePass
            ansible_ssh_private_key_file: /home/quobis/.ssh/id_rsa
