
- name: Enable universe and multiverse repository
  become: yes
  apt_repository:
      repo: "{{ item }}"
  loop:
      - "deb http://archive.ubuntu.com/ubuntu/ xenial universe"
      - "deb http://archive.ubuntu.com/ubuntu/ xenial-updates universe"
      - "deb http://security.ubuntu.com/ubuntu/ xenial-security universe"
      - "deb http://archive.ubuntu.com/ubuntu/ xenial multiverse"
      - "deb http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse"
      - "deb http://security.ubuntu.com/ubuntu/ xenial-security multiverse"

- name: Install pip3
  become: yes
  apt:
      update_cache: yes 
      name: python3-pip    

- name: install dependecies for Easysnmp
  become: yes
  apt:
      name:
          - libsnmp-dev
          - snmp-mibs-downloader
          - gcc
          - python-dev

- name: install pip easysnmp
  pip:
    name: easysnmp
    executable: pip3

- name: Create installation snmp-agent-communications directory
#   become: yes
  file: "path={{ snmp_installation_path }} state=directory mode=0755"

- name: copy script and config
  # become: yes
  copy:
      src:  snmp-agent-communications.py
      dest: "{{ snmp_installation_path }}/snmp-agent-communications.py"
      mode: 0755 

- name: generate config and copy 
#   become: yes
  template: "src=snmp-agent-communications.yml.j2 dest={{ snmp_installation_path }}/snmp-agent-communications.yml mode=644"

- name: snmp-agent-communication | Create Unit file
  become: yes
  template: src=snmp-agent-communication.service.j2 dest=/lib/systemd/system/snmp-agent-communication.service mode=644

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
 
- name: snmp-agent-communication | Start and enable script
  become: yes
  #daemon_reload: yes
  service: name=snmp-agent-communication.service state=started enabled=yes

- name: install pip requests for 
  pip:
    name: requests
    executable: pip3

- name: copy script to get QoS values
  # become: yes
  copy:
      src: getQoSValues.py
      dest: "{{ snmp_installation_path }}/getQoSValues.py"
      mode: 0755 
