---
- debug: var=ansible_facts
- debug: var=vars

- name: Install snmp, snmpd and libsnmp-dev
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - snmp
    - snmpd
    - libsnmp-dev

- name: stop snmpd
  become: yes
  service:
    name: snmpd
    state: stopped

- name: Deploy snmp template configuration for VNF-MS
  become: yes
  template:
    src: templates/snmp.conf.j2
    dest: /etc/snmp/snmpd.conf
  when: host_type == "type-vnf-ms"

- name: Deploy snmp template configuration for VNF-WAC
  become: yes
  template:
    src: templates/snmp.conf-wac.j2
    dest: /etc/snmp/snmpd.conf
  when: host_type == "type-vnf-wac"

- name: Deploy snmp template configuration  VNF-RP
  become: yes
  template:
    src: templates/snmp-rp.conf.j2
    dest: /etc/snmp/snmpd.conf
  when: host_type == "type-vnf-rp"


- name: Create snmpv3 user
  become: yes
  raw: "net-snmp-create-v3-user  -ro -A {{ snmp_auth_password }} -a {{ snmp_auth_protocol }} -X {{ snmp_privacy_password }} -x {{ snmp_privacy_protocol }} {{ snmp_security_username }}"

- name: start snmpd
  become: yes
  service:
    name: snmpd
    state: started

- name: Add env var to systemctl script of pm2 to monit process with snmpd
  become: yes
  lineinfile:
    path: /etc/systemd/system/pm2-root.service
    insertafter: "^Environment="
    line: "Environment=PM2_DAEMON_TITLE={{ name_pm2_process }}"
  when: host_type == "type-vnf-wac"


- name: reload systemd
  become: yes
  command: systemctl daemon-reload
 
- name: pm2-root | Start and enable script
  become: yes
  #daemon_reload: yes
  service: name=pm2-root.service state=restarted enabled=yes
  when: host_type == "type-vnf-wac"
